// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhgycynqsscshvzkkvha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoZ3ljeW5xc3Njc2h2emtrdmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTExMzUsImV4cCI6MjA2NDI4NzEzNX0.nAfIak8onIbjUfYGdjelQy8JjmaqzWg9Z2n2zCMsDK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);